input {
  beats {
    port => 5044
  }
}

filter {
  if [kubernetes][container][name] == "java-app" {
    grok {
      match => { "message" => "%{COMBINEDAPACHELOG}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "k8s-logs-%{+YYYY.MM.dd}"
  }
}